name: check

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Check Types
        run: yarn typecheck
      - name: Lint ESLint & Prettier
        run: yarn lint
